name: build-kernel
on:
  workflow_dispatch:
jobs:
  build-ksu:
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      #- name: Setup build environment
      #  run: curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | bash -
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git ccache pngcrush schedtool maven lib32ncurses5-dev xsltproc libxml2-utils squashfs-tools lzop flex build-essential bc libssl-dev libswitch-perl libxml-simple-perl zip unzip g++-multilib bison gperf zlib1g-dev automake device-tree-compiler
          sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+rx /usr/local/bin/repo
      - name: Clone repo and sync
        run: |
          repo init -u https://github.com/bryanyee33/kernel_manifest -b uvite-xiaomi-sm8450 --depth=1
          repo sync
          mkdir -p kernel_platform/device/xiaomi/marble-kernel/dtbs
          mkdir -p .ccache
          ccache -M 10
          ccache -o sloppiness=time_macros -o cache_dir="$(pwd)/.ccache"
      - name: Include KSU
        run: |
          cd kernel_platform/xiaomi/sm8450
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
      - name: Include SUS-FS
        run: |
          HOME="$(pwd)"
          cp -r susfs4ksu/kernel_patches/* kernel_platform/xiaomi/sm8450
          cd kernel_platform/xiaomi/sm8450/KernelSU
          patch -p1 < 10_enable_susfs_for_ksu.patch
          cd ..
          patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch
          cd $HOME/susfs4ksu
          ./build_ksu_module.sh
          mv ksu_module_susfs.zip ..
      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.ccache
          key: aospa-marble
      - name: Build kernel
        run: |
          cd kernel_platform/xiaomi/sm8450
          ./build.sh marble
          ccache -s
      - name: Zip output
        run: |
          HOME="$(pwd)"
          cd kernel_platform/device/xiaomi/marble-kernel
          zip -r9 "${HOME}/blobs.zip" *
          cp Image $HOME/AnyKernel3
          cd $HOME/AnyKernel3
          zip -r9 "../marble-kernel.zip" * -x .git README.md *placeholder
      - name: Generate release tag
        id: tag
        run: echo "release_tag=AOSPA_KSU_GKI_$(date +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            marble-kernel.zip
            ksu_module_susfs.zip
          # blobs.zip
